# Generated by Django 4.1.10 on 2023-08-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='react',
            name='name',
        ),
        migrations.AddField(
            model_name='react',
            name='averageIncome',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='react',
            name='averageSuper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='react',
            name='sex',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterModelTable(
            name='react',
            table='core_react',
        ),
    ]
